name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: caco3-k8s
    name: Build

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: rust:1.73-bookworm

    steps:
      - uses: actions/checkout@v3
      - name: Fix git on CI
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Test dangerous PR 
        run: |
          echo "This is dangerous pr"
